# Generated by Django 4.0.3 on 2022-03-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_vk_id', models.CharField(max_length=11, null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmembers',
            name='member_vk_id',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='member_vk_id',
        ),
        migrations.AddField(
            model_name='chatmembers',
            name='chat_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.members'),
        ),
        migrations.AddField(
            model_name='queues',
            name='queue_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.members'),
        ),
    ]
