# Generated by Django 4.0.3 on 2022-03-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='ChatMembers',
            new_name='ChatMember',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Queues',
            new_name='Queue',
        ),
        migrations.RenameModel(
            old_name='QueuesChats',
            new_name='QueueChat',
        ),
    ]
