# Generated by Django 4.0.3 on 2022-05-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_queue_member_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuechat',
            name='queue',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
