# Generated by Django 4.0.3 on 2022-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_remove_queuechat_queue_delete_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_queue', models.JSONField()),
            ],
        ),
    ]
