# Generated by Django 4.0.3 on 2022-05-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='members_queue',
            new_name='queue_members',
        ),
        migrations.AddField(
            model_name='queue',
            name='queue_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='QueueChat',
        ),
    ]
