# Generated by Django 4.0.3 on 2022-05-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_rename_members_queue_queue_queue_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_datetime', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.chat')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.queue')),
            ],
        ),
    ]
